backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cars"
    label: "Cars"
    folder: "cars"
    create: true
    slug: "{{year}}-{{make}}-{{model}}-{{vin}}"
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Example: 2017 Hyundai Elantra SE" }

      - { label: "Year", name: "year", widget: "string", hint: "Example: 2017" }
      - { label: "Make", name: "make", widget: "string", hint: "Example: Hyundai" }
      - { label: "Model", name: "model", widget: "string", hint: "Example: Elantra" }

      - { label: "Mileage", name: "mileage", widget: "string", hint: "Example: 125000 miles" }
      - { label: "VIN", name: "vin", widget: "string" }
      - { label: "Price", name: "price", widget: "string", hint: "Example: 7995" }

      - { label: "Main Photo", name: "image", widget: "image", required: false }

      - label: "More Photos"
        name: "gallery"
        widget: "list"
        required: false
        summary: "{{fields.photo}}"
        fields:
          - { label: "Photo", name: "photo", widget: "image" }

      - { label: "Description", name: "body", widget: "text", required: false }
